from .Athlete import Athlete
from .Branch import Branch
from .CategoryItem import CategoryItem
from .Coach import Coach
from .Communication import Communication
from .Competition import Competition
from .Judge import Judge
from .Level import Level
from .License import License
from .Person import Person
from .Punishment import Punishment
from .SportsClub import SportsClub
from .Menu import Menu
from .MenuAdmin import MenuAdmin
from .City import City
from .Country import Country
from .SportClubUser import SportClubUser
from .ClubRole import ClubRole
from .DirectoryCommission import DirectoryCommission
from .DirectoryMemberRole import DirectoryMemberRole
from .DirectoryMember import DirectoryMember
from .BeltExam import BeltExam
from .MenuAthlete import MenuAthlete
from .MenuCoach import MenuCoach
from .MenuDirectory import MenuDirectory
from .MenuReferee import MenuReferee
from .MenuClubUser import MenuClubUser
from .SimpleCategory import SimpleCategory
from .CompAthlete import CompAthlete
from .CompCategory import CompCategory
from .GrupForReport import GrupForReport
from .Weight import Weight
from .FedsportalModels import AdminProfiles

