# Generated by Django 2.2.6 on 2021-04-16 09:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sbs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abirimparametre',
            name='birim',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sbs.Abirim', verbose_name='Birim'),
        ),
    ]
