# Generated by Django 2.2.6 on 2021-04-16 09:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sbs', '0002_auto_20210416_0955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adosya',
            name='klasor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sbs.Aklasor'),
        ),
        migrations.AlterField(
            model_name='adosyaparametre',
            name='dosya',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sbs.Adosya'),
        ),
        migrations.AlterField(
            model_name='adosyaparametre',
            name='parametre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sbs.AbirimParametre'),
        ),
        migrations.AlterField(
            model_name='aklasor',
            name='birim',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sbs.Abirim', verbose_name='Birim'),
        ),
    ]
