# Generated by Django 2.2.6 on 2021-04-26 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sbs', '0004_auto_20210426_1448'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aevrak',
            name='file',
            field=models.FileField(max_length=1000, upload_to=''),
        ),
    ]
