# Generated by Django 2.2.6 on 2021-05-04 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sbs', '0006_auto_20210427_1027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aklasor',
            name='finishyear',
            field=models.IntegerField(blank=True, null=True, verbose_name='Bitiş Yılı'),
        ),
        migrations.AlterField(
            model_name='aklasor',
            name='startyear',
            field=models.IntegerField(blank=True, null=True, verbose_name=' Başlangıç Yılı'),
        ),
    ]
